/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ch.zhaw.pm3.aBrain;

import ch.zhaw.pm3.aBrain.frontend.ControlledScreens;
import ch.zhaw.pm3.aBrain.frontend.controller.ScreenController;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

/**
 * This class is the main class of the application.
 * It starts the application and loads the first screen.
 *
 * @author baermlau, hessnat1, jasarard, wilphi01, zimmelu5
 * @version 1.0
 */
public class aBrain extends Application{
    
    public enum Screen{
        LOGIN("LoginScreen"), HOME("HomeScreen"), SETTINGS("SettingsScreen"),
        PHARMACY("PharmacyScreen"), JOURNAL("JournalScreen"), COMMUNITY("CommunityScreen"),
        MED_DATA_OVERVIEW("MedDataOverview"), MED_NAME("MedNameScreen"),
        MED_ADMIN_INTERVAL("MedAdminIntervalScreen"), MED_DATA_START_INTERVAL("MedStartIntervalScreen"),
        MED_ADMIN_TIME("MedAdminTimeScreen"), MED_STOCK("MedStockScreen"),
        MED_X_DAYS_INTERVAL("MedxDaysIntervalScreen"), MED_X_HOURS_INTERVAL("MedxHoursIntervalScreen"),
        MED_SINGULAR_OCCURRENCE("MedSingularOccurrenceScreen"), MED_WEEKDAY_INTERVAL("MedWeekdayIntervalScreen"),
        MED_INTAKE_TIME("MedIntakeTime");


        String name;
    
        Screen(String name) {
            this.name = name;
        }
    
        public String getName() {
            return name;
        }
    
        public String getFXMLPath() {
            return "design/fxml/"+name+".fxml";
        }
    }


    private ScreenController screenController = ScreenController.getInstance();
    
    /**
     * The entry point of application.
     *
     * @param args the input arguments
     */
    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        loadAllScreens();
        mainWindow(primaryStage);
    }

    private void mainWindow(Stage stage) {
        try {
            Scene scene = new Scene(screenController.getScreen(Screen.LOGIN));
            stage.setScene(scene);
            stage.setResizable(false);
            stage.show();
        } catch (Exception e) {
            //TODO: add logger
            System.out.println("mainWindow" + e.getMessage());
        }
    }

    private void loadAllScreens() {
        for(Screen screen : Screen.values()){
            loadScreen(screen);
        }
    }

    private void loadScreen(Screen screen) {
        try {
            FXMLLoader loader = new FXMLLoader(getClass().getResource(screen.getFXMLPath()));
            Parent loadScreen = loader.load();
            ControlledScreens controlledScreens = loader.getController();
            screenController.setParentsAndController(screen, loadScreen, controlledScreens);
        } catch (Exception e) {
            //TODO: add logger
            System.out.println("loadScreen: " + e.getMessage());
        }
    }
}
